--  This package was generated by the Ada_Drivers_Library project wizard script
package ADL_Config is
   Architecture                   : constant String  := "ARM";               -- From board definition
   Board                          : constant String  := "MicroBit_v2";       -- From user input
   Boot_Memory                    : constant String  := "flash";             -- From user input
   CPU_Core                       : constant String  := "ARM Cortex-M4F";    -- From mcu definition
   Device_Family                  : constant String  := "nRF52";             -- From board definition
   Device_Name                    : constant String  := "nRF52833xxAA";      -- From board definition
   Has_Ravenscar_Full_Runtime     : constant String  := "True";              -- From board definition
   Has_Ravenscar_SFP_Runtime      : constant String  := "True";              -- From board definition
   Has_ZFP_Runtime                : constant String  := "True";              -- From board definition
   Max_Mount_Name_Length          : constant         := 128;                 -- From user input
   Max_Mount_Points               : constant         := 2;                   -- From user input
   Max_Path_Length                : constant         := 1024;                -- From user input
   Number_Of_Interrupts           : constant         := 128;                 -- From MCU definition
   Runtime_Name                   : constant String  := "ravenscar-full-nrf52833";   -- From user input
   Runtime_Name_Suffix            : constant String  := "cortex-m4f";        -- From board definition
   Runtime_Profile                : constant String  := "ravenscar-full-nrf52833";     -- From user input
   Use_Startup_Gen                : constant Boolean := False; -- From user input
   Vendor                         : constant String  := "Nordic";            -- From board definition
end ADL_Config;
