name: Ada (GNAT)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'true'
      
    - name: Set up GNAT toolchain
    run: >
        sudo apt-get update &&
        sudo apt-get install gnat gprbuild
        
    - name: Build
    run:  PATH="$PATH:/opt/gnat/bin" gprbuild -j0 -p

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: MainProject
        path: obj/main
		   
							  
									   
