name: Ada (GNAT)
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
     
      - name: Setup GNAT ARM Toolchain
        run: >
          wget -q https://github.com/alire-project/GNAT-FSF-builds/releases/download/gnat-14.2.0-1/gnat-arm-elf-linux64-x86_64-14.2.0-1.tar.gz           
          tar xf gnat-arm-elf-linux64-x86_64-14.2.0-1.tar.gz          
      - name: Build
        run: 'PATH="$PATH:/opt/gnat/bin" gprbuild -j0 -p'
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ITRS
          path: obj/main
