name: Ada (GNAT)
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Setup GNAT ARM Toolchain
        run: |
          wget -q https://github.com/alire-project/GNAT-FSF-builds/releases/download/gnat-14.2.0-1/gnat-arm-elf-linux64-x86_64-14.2.0-1.tar.gz
          tar xf gnat-arm-elf-linux64-x86_64-14.2.0-1.tar.gz
          echo "${PWD}/gnat-arm-elf-linux64-x86_64-14.2.0-1/bin" >> $GITHUB_PATH        

          wget -q https://github.com/alire-project/GNAT-FSF-builds/releases/download/gprbuild-22.0.0-1/gprbuild-x86_64-linux-22.0.0-1.tar.gz
          tar xf gprbuild-x86_64-linux-22.0.0-1.tar.gz
          echo "${PWD}/gprbuild-x86_64-linux-22.0.0-1/bin" >> $GITHUB_PATH
      
      - name: Build
        run: 'gprbuild -j0 -P Code/itrs.gpr Code/src/main.adb -cargs:ada -gnatef'
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ITRS
          path: Code/obj/main
